### ISSUE TITLE
tool o pagina admin

### ISSUE THREAD

**Issue by profmancusoa** [profmancusoa/LambsOfFame#2]
- possibilità di inserire/rimuovere un punteggio per uno o più studenti studenti per una materia di una classe

**Comment by marcoce005** [comment]
Ho fatto lo script per aggiungere un'intera classe dato il JSON con gli studenti  e lo script per assegnare il punteggio ad uno studenti in una specifica materia (il punteggio viene aggiunto anche nella classifica generale)
Faccio una cartella script nel progetto svelte?

**Comment by profmancusoa** [comment]
> Ho fatto lo script per aggiungere un'intera classe dato il JSON con gli studenti e lo script per assegnare il punteggio ad uno studenti in una specifica materia (il punteggio viene aggiunto anche nella classifica generale) Faccio una cartella script nel progetto svelte?

si perfetto. aggiungili in scripts o utils

**Comment by profmancusoa** [comment]
ok come discusso va bene così com'è con l'autenticazione alla pressione del submit
