### ISSUE TITLE
nomi documenti leggibili

### ISSUE THREAD

**Issue by profmancusoa** [profmancusoa/LambsOfFame#6]
i documenti del DB devono avere un nome "leggibile"

\<cognome\>_\<nome\>_\<YYYYMMDD\>_\<HHMMSS\>

così abbiamo la garanzia che sono univoci siccome  è praticamente impossibile che riesco ad inserire due entry nello stesso secondo

**Comment by marcoce005** [comment]
Forse conviene inserire anche delle informazioni sulla meteria, ho fatto delle prove e, caricando una lista di punti tramite codice, il timestamp è uguale per tutta la lista. 
Inserendo la materia abbiamo modo di trovare la query più velocemente inoltre inseriamo un altro campo rendendo ancora più univoca la dicitura.

**Comment by marcoce005** [comment]
https://github.com/profmancusoa/LambsOfFame/commit/2cd35f27879f6d42959e9fa8315d6cbc664a1865

**Comment by profmancusoa** [comment]
bene,
però per averli meglio ordinati

cambia Furina_Emanuele_reti_02-08-2024_16:40:49  in ----> Furina_Emanuele_reti_2024_08-02-2024_16:40:49


grazie

**Comment by marcoce005** [comment]
Ho inserito anche i millisecondi per aver maggior unicità. 
https://github.com/profmancusoa/LambsOfFame/commit/a9c740fc9de357ab03fc401bc7a539cdff670306

**Comment by profmancusoa** [comment]
molto bene @marcoce005
